# Question 1:

In [ ]:
import numpy as np

arr= np.arange( start=2, stop=50, step=3 )
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2:

In [ ]:
import numpy as np

lst1 = [] 
print("Enter 5 elements : ")
for i in range(0, 5): 
    ele = int(input()) 
    lst1.append(ele)

lst2 = [] 
print("Enter 5 elements : ")
for i in range(0, 5): 
    ele = int(input()) 
    lst2.append(ele)

l1= np.array(lst1)
l2= np.array(lst2)
c= np.concatenate((l1, l2))
print(c)
print(np.sort(c))

Enter 5 elements : 
2
7
4
0
1
Enter 5 elements : 
6
5
3
9
8
[2 7 4 0 1 6 5 3 9 8]
[0 1 2 3 4 5 6 7 8 9]


# Question 3:

In [ ]:
import numpy as np
 
arr = np.array( [[ 1, 2, 3], [ 4, 2, 5]] )
 
print("No. of dimensions: ", arr.ndim)
 
print("Size of array: ", arr.size)

No. of dimensions:  2
Size of array:  6


# Question 4:

In [ ]:
import numpy as np

print("1D array is :")
arr1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr1d)
print("\n1D array converted into 2D array")
arr2d= np.reshape(arr1d, (2, 5))
print(arr2d)


1D array is :
[0 1 2 3 4 5 6 7 8 9]

1D array converted into 2D array
[[0 1 2 3 4]
 [5 6 7 8 9]]


# Question 5:

In [ ]:
import numpy as np 
  
a = np.array([[1, 2], [3, 4]]) 
b = np.array([[5, 6], [7, 8]]) 
print("Vertical stacking:\n", np.vstack((a, b))) 
print("\nHorizontal stacking:\n", np.hstack((a, b))) 

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


# Question 6:

In [ ]:
l1 = [] 
print("Enter 7 Unique Numbers : ")
for i in range(0, 7): 
    ele = int(input()) 
    l1.append(ele)

s1 = set(l1)
val = len(s1)
lval = len(l1)
uval = lval-val
print("Unique Items Numbers are: ",uval)

Enter 7 Unique Numbers : 
3
6
4
6
4
3
5
Unique Items Numbers are:  3
